Add description for specification's intended audience
w3c/WebID pull request #29
Opened 2024-01-02 14:14 UTC by csarven

Clarifying who this specification is for signals to the reader whether and what they might be able to get out of this specification. This text - which could be adapted as the spec progresses - can also serve as an editorial guide on expressing certain notions and structuring.

2024-01-03 15:51 UTC, kidehen commented
The intended audience of a specification is crucial. This is a very important fix that the WebID Specification doc needs.

2024-01-03 16:03 UTC, kidehen requested changes
<ul>
  <li>Anyone that wants to understand the architectural principles and notions underlying a WebID.</li>
  <li>Content publishers that want to allocate identifiers to denote agents, unambiguously.</li>
  <li>Server application developers who want provide client applications with WebIDs and their associated agent descriptions.</li>
  <li>Client application developers who want use a WebID for unambiguous agent naming.</li>
  <li>Specification authors who want to build additional specifications around WebID e.g., identity authentication protocols.</li>
</ul>

2024-01-05 10:33 UTC, jacoscaz commented
_/chair hat off_

+1 from me as-is.

> which could be adapted as the spec progresses

Absolutely, but this is a good starting point.

2024-01-10 20:22 UTC, TallTed requested changes

2024-01-10 20:22 UTC, TallTed commented on spec/identity/index.html
> +</ul>
Applying @kidehen's suggested tweaks, with some tweaks of my own
```suggestion
  <li>Anyone who wants to understand the architectural principles and notions underlying WebID</li>
  <li>Content publishers who want to allocate identifiers to denote agents, unambiguously</li>
  <li>Server application developers who want to provide client applications with WebIDs and associated agent descriptions</li>
  <li>Client application developers who want to use a WebID to unambiguously identify their applications as agents</li>
  <li>Specification authors who want to extend WebID via additional specifications, e.g., identity authentication protocols</li>
</ul>
```

2024-01-10 21:00 UTC, kidehen commented
@TallTed, 

"name" rather than "denote" for consistency with the overarching theme of the spec.

2024-01-10 21:13 UTC, kidehen requested changes
```html
<li>Anyone who wants to understand the architectural principles and notions underlying WebID</li>
<li>Content publishers who want to allocate identifiers to denote agents, unambiguously</li>
<li>Server application developers who want to provide client applications with WebIDs and associated agent descriptions</li>
<li>Client application developers who want to use a WebID to unambiguously identify their applications as agents</li>
<li>Specification authors who want to extend WebID via additional specifications, e.g., identity authentication protocols</li>
 ```

2024-01-22 19:05 UTC, TallTed commented
> Why are there pull requests against the old ed spec?

Because relatively few relatively small changes to the old Editors Draft are expected to result in a document which can garner consensus approval.

> The CG is focussed on creating new documents.

Where does anything say that?

2024-01-22 19:07 UTC, TallTed commented
@kidehen's [later suggestion](https://github.com/w3c/WebID/pull/29#pullrequestreview-1814187199) has been applied to [my change request](https://github.com/w3c/WebID/pull/29#discussion_r1447926962).

2024-01-29 08:49 UTC, jacoscaz commented
@csarven would you be ok with me forking this and rebasing on main to maintain your contribution?

2024-01-31 18:59 UTC, jacoscaz commented
Closing in favor of #56 .

2024-01-31 18:59 UTC, closed without merging