Update with @dbooth-boston's improvements. Issue #2
w3c/WebID pull request #6
Opened 2022-02-27 13:57 UTC by csarven

This commit incorporates all of the improvements suggested by @dbooth-boston in https://lists.w3.org/Archives/Public/public-webid/2021Mar/0000.html with the exception of the first item:

>1. The "Latest editor's draft" link goes to
>https://dvcs.w3.org/hg/WebID/raw-file/tip/spec/identity-respec.html
>which has a "This version" link that is 404:
>http://www.w3.org/2005/Incubator/webid/spec/drafts/ED-webid-20121118

Created Issue #5 to address updates to URLs.

Merging this PR should close #2 in that #5 will supersede the remaining work.

2022-02-27 14:20 UTC, bblfish commented
Great. Thanks @csarven for adding those edits and thanks to @dbooth-boston for writing them up.

2022-02-27 18:19 UTC, jonassmedegaard commented on spec/identity/index.html
> +<p>When using URIs, it is possible to identify both a thing (which may exist outside of the Web) and a Web document describing the thing. For example, the person Bob is described on his homepage. Ali
Sentence is still broken - both URIs related to Bob (and are only used by Alice).

Last sentence, originally:
> Therefore, two URIs are needed, one for Alice and one for the homepage or a RDF document describing Alice.

Last sentence, proposed change:
> Therefore, two URIs are needed, one for Alice and one for the homepage or a RDF document describing **Bob**.

Last sentence, structurally correct:
> Therefore, two URIs are needed, one for **Bob** and one for the homepage or a RDF document describing **Bob**.

(or alternatively, keep original last sentence talking about links to Alice, and instead swap Alice and Bob earlier in the paragraph).

2022-02-27 18:23 UTC, jonassmedegaard commented on spec/identity/index.html
> +The document can, for example, contain relations to other document depicting the WebID referent, or it can relate the WebID to principals used by different authentication protocols.
Seems the intent of the edit here was to relax from talking about a single other document to potentially plural other documents.
Seems to me that the word **document** should then consequently be changed to plural form **documents**.

2022-02-27 18:24 UTC, jonassmedegaard commented on spec/identity/index.html
> +The document can, for example, contain relations to other document depicting the WebID referent, or it can relate the WebID to principals used by different authentication protocols.
i.e. not "relations to other document" but "relations to other document**s**"

2022-02-27 18:38 UTC, csarven commented on spec/identity/index.html
> +<p>When using URIs, it is possible to identify both a thing (which may exist outside of the Web) and a Web document describing the thing. For example, the person Bob is described on his homepage. Ali
The example starts off with Bob so it'd be clearer to stick to Bob. Updated in https://github.com/w3c/WebID/pull/6/commits/1f05783bce6f9df6ea7fc08b5bc1c489bd564fb2

2022-02-27 18:42 UTC, csarven commented on spec/identity/index.html
> +The document can, for example, contain relations to other document depicting the WebID referent, or it can relate the WebID to principals used by different authentication protocols.
Indeed. This is my typo! https://github.com/w3c/WebID/pull/6/commits/76b3df96417deb9055b1f4922ac2e2c044a6be71

2022-02-27 19:11 UTC, jonassmedegaard commented
Looks good to me now. Thanks, @csarven.

2022-09-01 18:19 UTC, bblfish commented
Thanks for this PR of David Booths' proposed improvements. Unless anyone says anything, I will commit this PR.

2022-09-01 18:33 UTC, TallTed commented on spec/identity/index.html
> +<dd>A Server is a machine, contactable at a domain name or IP address, that hosts globally accessible Services.</dd>
```suggestion
<dd>A Server is a machine, contactable at a domain name or IP address, that hosts Services which are accessible over the network. Accessibility may be global, local, or anywhere in between, depending on firewall, service, and related policy configurations.</dd>
```

2022-09-01 18:35 UTC, TallTed commented on spec/identity/index.html
> +<p>When using URIs, it is possible to identify both a thing (which may exist outside of the Web) and a Web document describing the thing. For example, the person Bob is described on his homepage. Ali
```suggestion
<p>When using URIs, it is possible to identify both a thing (which may exist outside of the Web) and a Web document describing the thing. For example, the person Bob is described on his homepage. Alice may not like the look of Bob's homepage, but may want to link to the person Bob. Therefore, two URIs are needed, one for Bob and one for the homepage or an RDF document describing Bob.</p>
```

2022-09-01 18:37 UTC, TallTed commented on spec/identity/index.html
> +A WebID Profile is a public document that may contain public as well as personal information about the agent identified by the WebID.
```suggestion
A WebID Profile is a public document that may contain public as well as private information about the agent identified by the WebID.
```

2022-09-01 18:37 UTC, TallTed requested changes
A few improvements to the improvements...

2022-09-01 19:05 UTC, csarven commented on spec/identity/index.html
> +A WebID Profile is a public document that may contain public as well as personal information about the agent identified by the WebID.
That is a proposal to change something that's non-editorial.

I suggest to NOT include this suggestion in this PR because PR https://github.com/w3c/WebID/pull/7 will cover it separately and it is based on an issue. Avoid merge conflict later.

2022-09-01 19:09 UTC, bblfish commented on spec/identity/index.html
> +<dd>A Server is a machine, contactable at a domain name or IP address, that hosts globally accessible Services.</dd>
Mhh I wonder how much we want to get into the details here... We should look at why these definitions are there at all. I did not notice them being used that much. WebIDs really work if they are global identifiers. So that is a SHOULD as there is no way to guarantee they are globally available, and it allows for local exceptions.

2022-09-01 19:17 UTC, csarven commented on spec/identity/index.html
> +<dd>A Server is a machine, contactable at a domain name or IP address, that hosts globally accessible Services.</dd>
This may be useful to some readers but I think it is cumbersome. If we are to update this definition, I'd suggest to keep the current text as is and then reference "server" as defined in RFC 7230 ( https://www.rfc-editor.org/rfc/rfc7230#section-2.1 ) or RFC 8110 ( https://www.rfc-editor.org/rfc/rfc9110#section-3.3-2 ) - I believe that is what's intended. That can be part of a separate PR.

2022-09-01 19:29 UTC, TallTed commented on spec/identity/index.html
> +<dd>A Server is a machine, contactable at a domain name or IP address, that hosts globally accessible Services.</dd>
This definition is not of a "WebID Server"; it's of a "Server".

I'm not attached to the specifics of this definition; the part I have issue with is "globally accessible", which I think is not so often the case.

Even if this *is* defining "WebID Server", I don't think "globally accessible" is mandatory; it only needs to be accessible by those the WebID referent wants to access their WebID Document.

I think I would also be fine with removing these definitions of Service and Server, and linking out to relevant RFC, Wikipedia, or other pre-existing definitions in the world.

2022-09-01 19:31 UTC, TallTed commented on spec/identity/index.html
> +<dd>A Server is a machine, contactable at a domain name or IP address, that hosts globally accessible Services.</dd>
Maybe this is more acceptable to folks --
```suggestion
<dd>A Server is a machine, contactable at a domain name or IP address, that hosts Services which are accessible over the network.</dd>
```

2022-09-02 15:46 UTC, TallTed commented on spec/identity/index.html
> +<dd>A Service is an agent listening for requests at a particular IP address on a given Server.</dd>
To better match `Server` definition...
```suggestion
<dd>A Service is an agent listening for requests at a particular domain name or IP address on a given Server.</dd>
```

2022-09-02 15:47 UTC, TallTed commented on spec/identity/index.html
> +<dd>A Server is a machine, contactable at a domain name or IP address, that hosts Services which are accessible over the network.</dd>
To allow for cloud as well as on-site deployments...
```suggestion
<dd>A Server is a physical or virtual machine, contactable at a domain name or IP address, that hosts Services which are accessible over the network.</dd>
```

2022-09-03 09:53 UTC, bblfish commented
Can I merge?

2022-09-04 18:59 UTC, merged

2022-09-04 19:00 UTC, bblfish commented
I left the following comment in the PR, not realising that it was not visible here:

> I think we have consensus on these changes. David Booth made his comments over a year ago, and this caputers the editorial changes proposed by him. 

> I also opened an issue to see how we can deal with his comments on the "sense" side of the diagram. https://github.com/w3c/WebID/issues/11

2022-09-06 04:12 UTC, TallTed commented
International collaboration being what it is, I feel it should be noted that @bblfish asked whether this was ready to merge at ~6am ET on Sept 3, a Saturday, and merged it at ~3pm ET on Sept 4, a Sunday. It's great that some folks find spec work to be worthy of weekend time, but it should not be assumed that others are doing the same.

In other words — please don't ask for feedback during near-universal off-hours, and even more please don't act on (lack of) feedback before most people are likely to have seen the request.

2022-09-06 05:59 UTC, csarven commented
PR was open for 189 days. It was reviewed. Change requests were integrated. There are approvals and no objections.

2022-09-06 06:07 UTC, bblfish commented
@TallTed wrote
> In other words — please don't ask for feedback during near-universal off-hours, and even more please don't act on (lack of) feedback before most people are likely to have seen the request.

Ok, point noted @TallTed .  Thanks for your contributions too.

don't think there was a problem in this case as @csarven noted, but it could be a problem on future PRs.

2022-09-06 17:36 UTC, TallTed commented on spec/identity/index.html
> +A WebID Profile is a public document that may contain public as well as personal information about the agent identified by the WebID.
How is this non-editorial?  I assert that the (intended) meaning is the same whether the word is `personal` or `private`, and that it is clearer to say `private` than `personal`. Indeed, the current `main` fork has this as `private`.  Further, this section is **non-normative**, so *any* change made here is editorial!  (This is currently line 634; the section is labeled as non-normative in line 632.)

It is poor form to mark a suggested change which is being rejected as "resolved" without concurrence from the change suggester.

2022-09-06 17:42 UTC, TallTed commented
@bblfish @csarven — 

I made this comment against [this suggested change](https://github.com/w3c/WebID/pull/6/files?diff=split&w=1#r960986388), but because it's marked RESOLVED, it's invisible. So, I'm re-posting [my comment](https://github.com/w3c/WebID/pull/6/files?diff=split&w=1#r963997989) here —

> How is this non-editorial?  I assert that the (intended) meaning is the same whether the word is `personal` or `private`, and that it is clearer to say `private` than `personal`. Indeed, the current `main` fork has this as `private`.  Further, this section is **non-normative**, so *any* change made here is editorial!  (This is currently line 634; the section is labeled as non-normative in line 632.)
>
> It is poor form to mark a suggested change which is being rejected as "resolved" without concurrence from the change suggester.

2022-09-06 17:47 UTC, TallTed commented
@csarven — Yes, this PR was open for 6 months.  I'm not surprised by that, given that the WebID CG has been in a coma for some years.

There has been substantial activity on this PR in recent days; one might say that the coma is ending.  Had the recent comments been made 6 months ago, I do not think they would have received quite the same treatment as they have, having been made only a week or so ago.

2022-09-06 18:55 UTC, csarven commented on spec/identity/index.html
> +A WebID Profile is a public document that may contain public as well as personal information about the agent identified by the WebID.
It is "non-editorial" in the sense that I'd consider the change request to benefit from both group awareness as well as consensus. This is of course subjective and some editors may indeed exercise their "right" to change more strongly. I chose not to in this particular PR because the PR is intended to focus on dbooth's suggestions as opposed to any other change that could be made along the way.

Moreover, changing non-normative text doesn't in and itself constitute "editorial". Non-normative text could be "important" and very well need further Group deliberation.

As mentioned earlier, the suggested change is already in place as per PR 7 and went through the process in the context of where it is relevant, i.e., not in this PR.

I will go ahead and unresolve this conversation now. Feel free to resolve the conversation if you think my response is adequate. Otherwise, indicate what you'd like to discuss further.

2022-09-06 19:21 UTC, TallTed commented on spec/identity/index.html
> +A WebID Profile is a public document that may contain public as well as personal information about the agent identified by the WebID.
Weirdly, GitHub doesn't offer me a path to resolve the suggestion, which I think is *now* appropriate, after all the threads within and linked from this PR.

Regarding the [bits and pieces above](https://github.com/w3c/WebID/pull/6#discussion_r964064337) — I'm usually fine with being asked to take tangential change suggestions to distinct PRs and/or Issues. Unfortunately, marking such suggestions as Resolved hides them in most of the GitHub UI, even if you make a comment there as you do so. I ask, therefore, that when you wish to reject a suggested change, for whatever reason, you state that reason in a comment on the suggestion _and await a response_ from the suggester before marking it Resolved. That will let us modify our suggestions, move them to distinct PRs or Issues, etc.

2022-09-06 19:29 UTC, csarven commented on spec/identity/index.html
> +A WebID Profile is a public document that may contain public as well as personal information about the agent identified by the WebID.
In this particular case I assumed the explanation was adequate for us to move on, so resolved it. I don't disagree with your suggestion to await for a response - I do normally let conversations remain open as reasonably as possible. Resolving conversation now :)