feat: new definitions
w3c/WebID pull request #60
Opened 2024-02-07 08:11 UTC by jacoscaz

Hi all,

This PR aims at porting the new definitions from #37 into our working draft. Some notes:

- The group has expressed multiple times, in the past, a preference for small and focused PRs. These kinds of PRs are not my forte, to use a euphemism, so I've decided to start hyper-focused and let the group suggest further additions.

- Together with the definitions from #37, you will notice that I've also added a paragraph that defines the set of required statements that MUST appear within a WebID Profile Document. I've done so because, for some us, defining what a WebID Profile Document is implies a minimum description of how such a document may be validated in order to tell it apart from any other RDF document. You can find notes and pointers about this in #37 but I just wanted to repeat this here for simplicity.

- You will notice that I have simplified the definitions, removing things like the MUST on Turtle (which is already stated elsewhere). That is intentional editorial choice as definitions should be concise and leave further elaboration and details for the appropriate sections.

Of course this is for everyone to review and comment upon but I'll tag those that have provided the most feedback on this topic: @kidehen @TallTed @webr3 @acoburn @woutermont and @jonassmedegaard .

2024-02-07 08:16 UTC, jacoscaz commented
Given that:

- This topic has been under discussion for a long time
- I've been tracking consensus on definitions in #37

I'd be inclined to set the deadline for review in two weeks from now, on 2024-02-21. However, I do acknowledge that the new requirements for the contents of a WebID Profile Document qualify as breaking and I'm open to move the deadline to four weeks from now, on 2014-03-06. IMHO, that would make for a really, really glacial pace of progress but the perception of pace is fairly subjective.

2024-02-07 09:02 UTC, melvincarvalho commented
As stated, I am in favour of a short [freeze](https://lists.w3.org/Archives/Public/public-webid/2024Jan/0030.html) on the evolution document

I would prefer instead [creating a serialization neutral definition of WebID](https://lists.w3.org/Archives/Public/public-webid/2024Feb/0002.html) which I believe has significant mind share in the group, and then to revisit this.  Or alternatively waiting until the Solid WG starts up.

I would urge the chair not to act unilaterally based on 2 week timelines.  To slow down, define WebID, in a standalone way, which is not tied to historical baggage, serialization debates, implementation debates, and hard fork considerations.

2024-02-07 09:14 UTC, melvincarvalho commented
> the contents of a WebID Profile Document qualify as breaking

-1

Strongly opposed to breaking changes

2024-02-07 13:33 UTC, kidehen approved these changes

2024-02-07 14:02 UTC, melvincarvalho requested changes
-1 no breaking changes please

2024-02-07 14:25 UTC, jacoscaz commented on spec/identity/index.bs
> +Device, etc.). A description of the Agent named by a WebID can be found in the
@webr3 thanks for reviewing! I'm not sure I understand this comment but if you are referring to the possibility of a WebID Profile Document to describe more than one Agent, that would be outside of the scope of this PR as it's something we've never explicitly discussed before. Also, it would likely conflict with the required presence of `foaf:primaryTopic`.

2024-02-08 00:07 UTC, TallTed requested changes
Small stuff

2024-02-08 00:07 UTC, TallTed commented on spec/identity/index.bs
> +that is named by it and the respective [=WebID Profile Document=].
```suggestion
that is named by it, and the respective [=WebID Profile Document=].
```

2024-02-08 00:07 UTC, TallTed commented on spec/identity/index.bs
> +[[#webid-profile-contents|Section 5]] defines the required and suggested
```suggestion
[[#webid-profile-contents|Section 5]] defines the required and some suggested
```

2024-02-08 08:57 UTC, jacoscaz commented on spec/identity/index.bs
> +Device, etc.). A description of the Agent named by a WebID can be found in the
@webr3 considering this resolved but 1) please reopen if I misunderstood and 2) do open a dedicated issue if you want to raise this with the group!

2024-02-08 12:25 UTC, jacoscaz commented on spec/identity/index.bs
> +Device, etc.). A description of the Agent named by a WebID can be found in the
@webr3 thanks for clarifying, addressed in https://github.com/w3c/WebID/pull/60/commits/aab8a04683de896404b6568db9005e0da4dce72b . As for URI vs. IRI vs. URL, we're hopefully going to address that whole topic in a different PR focused on that alone. Conversation ongoing in https://github.com/w3c/WebID/issues/10 .

2024-02-08 13:42 UTC, jacoscaz commented on spec/identity/index.bs
> +:: An identifier in the form of an HTTP IRI for unambiguously naming an Agent
Fixed, thanks!

2024-02-09 09:25 UTC, termontwouter reviewed
Good PR; minor suggestions.

2024-02-09 09:25 UTC, termontwouter commented on spec/identity/index.bs
> +familiar to any Social Network user.
```suggestion
the respective [=WebID Profile Document=].
```

I'd suggest removing this comparison, since it I am fairly certain that if I were to present a WebID (Profile) Document to a random Social Network user, they would not at all find it familiar.

Aside: this is how "Profile" slipped into the "WebID Profile Document" term, and one of the reasons it should be removed form that (though let's keep discussing that in https://github.com/w3c/WebID/issues/20).

2024-02-09 09:25 UTC, termontwouter commented on spec/identity/index.bs
> +[[#the-webid-http-uri|Section 3]] describes what a WebID is.
Not sure I'm a fan of this addition of "URI". If part of this PR is to make the distinction between "WebID" and "WebID (Profile) Document" more explicit (re @kidehen's suggestion), then it should automatically become clearer that we mean the URI (and not the document) when saying "WebID". Not a blocker though.

2024-02-09 09:25 UTC, termontwouter commented on spec/identity/index.bs
> +    describing the Agent named by the WebID itself.
The new phrasing reads ambiguously: for readers without background, the "which" more readily binds to "Agent" than to "HTTP URI". Suggestion:

```suggestion
:: An identifier in the form of an HTTP URI that unambiguously names an Agent
    and, when dereferenced, must always lead to a [=WebID Profile Document=]
    describing the Agent named by the WebID itself.    
```

2024-02-09 09:25 UTC, termontwouter commented on spec/identity/index.bs
> +    describing the Agent named by the WebID itself.
A nitpick: it is better not to use conformance terms like "must" in the terminology section. Just "... leads to ..." would suffice here, I believe.

2024-02-09 09:25 UTC, termontwouter commented on spec/identity/index.bs
> +:: A thing that does stuff.
Not sure we need this addition, but if so, it should be beter. Suggestion:

```suggestion
: <dfn>Agent</dfn>

:: An entity that performs or can perform an action, e.g. a person, an organization, a device.
```

2024-02-09 09:54 UTC, jacoscaz commented on spec/identity/index.bs
> +[[#the-webid-http-uri|Section 3]] describes what a WebID is.
Looks like I had already addressed this.

2024-02-09 10:01 UTC, termontwouter approved these changes

2024-02-09 18:40 UTC, TallTed requested changes
HTML file *really* needs to be made non-git-managed, i.e., it should exist *only* as an artifact produced by CI operating on the BS file!

2024-02-09 18:40 UTC, TallTed commented on spec/identity/index.bs
>      describing the Agent named by the WebID itself.
```suggestion
    which itself indicates that it describes the Agent named by the WebID.
```

2024-02-09 18:40 UTC, TallTed commented on spec/identity/index.bs
> +:: An entity that performs or can perform an action, e.g. a person, an organization, a device.
```suggestion
:: An entity that performs or can perform an action, e.g., a person, an organization, a device.
```

2024-02-09 18:40 UTC, TallTed commented on spec/identity/index.html
> +and, when dereferenced, must always lead to a <a data-link-type="dfn" href="#webid-profile-document" id="ref-for-webid-profile-document⑥">WebID Profile Document</a> describing the Agent named by the
```suggestion
and, when dereferenced, must always lead to a <a data-link-type="dfn" href="#webid-profile-document" id="ref-for-webid-profile-document⑥">WebID Profile Document</a> which itself indicates that it describes the Agent named by the WebID.</p>
```

2024-02-09 18:40 UTC, TallTed commented on spec/identity/index.html
> +     <p>An entity that performs or can perform an action, e.g. a person, an organization, a device.</p>
```suggestion
     <p>An entity that performs or can perform an action, e.g., a person, an organization, a device.</p>
```

2024-02-09 20:21 UTC, jacoscaz commented on spec/identity/index.html
> +and, when dereferenced, must always lead to a <a data-link-type="dfn" href="#webid-profile-document" id="ref-for-webid-profile-document⑥">WebID Profile Document</a> describing the Agent named by the
> HTML file really needs to be made non-git-managed, i.e., it should exist only as an artifact produced by CI operating on the BS file!

@TallTed I hear you - we'll get there. For the time being, you don't have to review `.html` files. I mean, of course you _can_ review them if it makes it easier but you don't need to correct the same things across both `.bs` and `.html`. I recompile the latter from the former with every batch of changes I add / make.

2024-02-09 20:27 UTC, jacoscaz commented
_/chair hat on_

Lots of comments and suggestions already. Thank you all! Following up to https://github.com/w3c/WebID/pull/60#issuecomment-1931500299 and given the participation, I'm setting the deadline for review on 2024-02-21.

2024-02-09 22:01 UTC, TallTed commented on spec/identity/index.bs
> +    and, when dereferenced, must always lead to a [=WebID Profile Document=]
I'll go along with removing the normative language, here. Still, for WebID to work as expected — as it has for the past decade — dereferencing that URI cannot *not* lead to a WebID Profile Document. Therefore —
```suggestion
    and, when dereferenced, always leads to a [=WebID Profile Document=]
```

2024-02-12 14:58 UTC, termontwouter commented
> HTML file _really_ needs to be made non-git-managed, i.e., it should exist _only_ as an artifact produced by CI operating on the BS file!

I agree. Discussing [here](https://github.com/w3c/WebID/discussions/63).

2024-02-21 13:26 UTC, jacoscaz commented
_/chair hat on_

Today's the deadline for review of this PR. I'll go ahead and merge as:

- It's been reviewed / approved by multiple participants.
- It's been mentioned in multiple "chair's overview" emails.
- It implements the consensus on definitions as tracked in #37.

Two strong objections have been raised, both by @melvincarvalho and both mentioned in https://github.com/w3c/WebID/pull/60#issuecomment-1931572536 (amongst other places):

> I would prefer instead [creating a serialization neutral definition of WebID](https://lists.w3.org/Archives/Public/public-webid/2024Feb/0002.html) which I believe has significant mind share in the group, and then to revisit this.

This is actually something that this PR already addresses. The new definitions are neutral WRT serialization formats. See https://github.com/w3c/WebID/pull/60/files#diff-274f5e91238718e44b429797b66dcdc21e2d576ae2e0e769f0279840e5196945R195 . 

> As stated, I am in favour of a short [freeze](https://lists.w3.org/Archives/Public/public-webid/2024Jan/0030.html) on the evolution of this document.

This has been addressed multiple times, some [by me](https://github.com/w3c/WebID/issues/58#issuecomment-1925809369) and some [by others](https://github.com/w3c/WebID/issues/41#issue-2079076941). 

As chair, I believe that these sustained objections have been considered and addressed adequately.

2024-02-21 13:28 UTC, merged