feat: uses IRI rather than URI or URL
w3c/WebID pull request #67
Opened 2024-03-18 08:47 UTC by jacoscaz

This PR closes long-standing #10 by replacing usages of "URI" with "IRI" and expanding on the relationship between IRIs, URIs and URLs, referencing and deferring to higher-level specs.

Though theoretically a breaking change, in practice this PR changes little to nothing. Setting the deadline for review in two weeks, on 2024-04-01.

2024-03-18 14:12 UTC, TallTed requested changes

2024-03-18 14:12 UTC, TallTed commented on spec/identity/index.html
> +  objects: 303 redirects and hash IRIs. Which one to use depends on the
```suggestion
  objects: 303 redirects and hash IRIs. Which one is best to use depends on the
```

2024-03-18 14:12 UTC, TallTed commented on spec/identity/index.html
> +   <div class="note" id="h_note_2" role="note"><a class="self-link" href="#h_note_2"></a> This specification follows the definitions and constraints expressed in <a href="https://www.w3.org/TR/rdf12-
```suggestion
   <div class="note" id="h_note_2" role="note"><a class="self-link" href="#h_note_2"></a> This specification follows the definitions and constraints expressed in <a href="https://www.w3.org/TR/rdf12-concepts/#section-IRIs">Section 3.2</a> of <a data-link-type="biblio" href="#biblio-rdf12-concepts" title="RDF 1.2 Concepts and Abstract Syntax">[rdf12-concepts]</a> regarding the use of IRIs within RDF syntax and
```

2024-03-18 14:12 UTC, TallTed commented on spec/identity/index.html
> +   <div class="note" id="h_note_2①" role="note"><a class="self-link" href="#h_note_2①"></a> This specification defers to the procedures defined in <a href="https://www.rfc-editor.org/rfc/rfc3987#sect
```suggestion
   <div class="note" id="h_note_2①" role="note"><a class="self-link" href="#h_note_2①"></a> This specification defers to the procedures defined in <a href="https://www.rfc-editor.org/rfc/rfc3987#section-3">Section 3</a> of <a data-link-type="biblio" href="#biblio-iri" title="Internationalized Resource Identifiers (IRIs)">[IRI]</a> regarding mapping and conversion between the IRI and URI spaces. </div>
```

2024-03-18 14:12 UTC, TallTed commented on spec/identity/index.html
> +   <p>The WebID IRI — <em>"<a href="http://www.w3.org/People/Berners-Lee/card#i">http://www.w3.org/People/Berners-Lee/card<strong>#i</strong></a>"</em> (containing the <strong>#i</strong> hash tag) —
```suggestion
   <p>The WebID IRI — <em>"<a href="http://www.w3.org/People/Berners-Lee/card#i">http://www.w3.org/People/Berners-Lee/card<strong>#i</strong></a>"</em> (containing the <strong>#i</strong> fragment identifier) — is an identifier that denotes (refers to) a
```

2024-03-18 14:12 UTC, TallTed commented on spec/identity/index.html
>  tag) — denotes the document describing the person (or more generally any agent)
```suggestion
   <p>The WebID Profile Document IRI — <em>"<a href="http://www.w3.org/People/Berners-Lee/card">http://www.w3.org/People/Berners-Lee/card</a>"</em> (without the <strong>#i</strong> fragment
identifier) — denotes the document describing the person (or more generally any agent)
```

2024-03-18 15:12 UTC, jacoscaz commented
Thank you @TallTed for reviewing!

2024-03-27 12:29 UTC, pmcb55 commented on spec/identity/index.bs
> +    [=WebID Profile Document=] which itself indicates that it describes the
Probably just a chicken-or-the-egg thing, so just noting that this will need to change once this other PR is merged: https://github.com/w3c/WebID/pull/69:
```suggestion
    [=WebID Document=] which itself indicates that it describes the
```

2024-03-27 12:49 UTC, pmcb55 approved these changes
For what it's worth(!), I'm happy to approve this PR (as I assume PR #69 will handle the 'WebID Document' renaming comments).

2024-03-27 19:05 UTC, pmcb55 commented
> FWIW still have security concerns regarding phishing attacks, with characters that look similar, regarding this change.

Yep @melvincarvalho, I think that's well understood, and clearly articulated even on the simple and accessible (i.e., readable for anyone, techie or not) Wikipedia page: https://en.wikipedia.org/wiki/Internationalized_Resource_Identifier (i.e., there's no need to read an entire spec for that to be made clear to people).

But I'm sure you'd agree with the entire RDF community for these past 20+ years that that understandable concern doesn't outweigh the clear advantages for our billions of non-Latin-alphabet-aware friends on the planet, as also clearly articulated on that Wikipedia page, i.e.: "_mostly, it makes it easier for users who are unfamiliar with the Latin (A–Z) alphabet_".

2024-03-27 19:47 UTC, melvincarvalho commented
> But I'm sure you'd agree with the entire RDF community for these past 20+ years that that understandable concern doesn't outweigh the clear advantages for our billions of non-Latin-alphabet-aware friends on the planet, as also clearly articulated on that Wikipedia page, i.e.: "_mostly, it makes it easier for users who are unfamiliar with the Latin (A–Z) alphabet_".

This is the wrong issue for that conversation, as it's off topic.  WebID is more about your `username` on the web.  That has different considerations from general RDF, and a higher interop burden.  In theory a WebID would never be seen by the end user, except for URI verification, but a foaf name could have lots of characters.  In any case, this is the wrong thread for such a debate.  Nevertheless interesting, thanks for the comment!

2024-05-28 13:12 UTC, closed without merging