fix: addresses David Booth's issues with diagram (closes #11)
w3c/WebID pull request #68
Opened 2024-03-18 10:07 UTC by jacoscaz

This PR is an attempt at addressing issues described in #11 and initially reported by David Booth in his [message to the list](https://lists.w3.org/Archives/Public/public-webid/2021Mar/0000.html) dating back to 2021.

In the interest of clarify, I've intentionally decoupled the overview of the relationships between a WebID, the corresponding WebID Profile Document and the Agent from the real-life example referencing TimBL's WebID.

Setting the deadline for review in two weeks, on 2024-04-01.

Do not bother reviewing the `spec/identity/index.html` as that's automatically updated by our current CI setup based on the contents of `spec/identity/index.bs`. We'll sort this out in a separate issue / PR.

Links to the rendered files:

- main branch: https://w3c.github.io/WebID/spec/identity/index.html
- this PR: https://htmlpreview.github.io/?https://github.com/jacoscaz/WebID/blob/fix/david-booth-issues-with-diagram/spec/identity/index.html

2024-03-18 14:13 UTC, TallTed requested changes

2024-03-18 14:13 UTC, TallTed commented on spec/identity/index.html
> +   <p>The WebID Profile Document URI <code>https://example.org/ident</code> (without the <strong>#me</strong> hash tag) denotes the document describing the agent  who is the referent of the
```suggestion
   <p>In the illustration above, the WebID URI <code>https://example.org/ident#me</code> (containing the <strong>#me</strong> fragment identifier) is an identifier that denotes (refers to) an
agent.</p>
   <p>The WebID Profile Document URI <code>https://example.org/ident</code> (without the <strong>#me</strong> fragment identifier) denotes the document describing the agent  who is the referent of the
```
```suggestion
   <p>In the illustration above, the WebID URI <code>https://example.org/ident#me</code> (containing the <strong>#me</strong> hash tag) is an identifier that denotes (refers to) an
agent.</p>
   <p>The WebID Profile Document URI <code>https://example.org/ident</code> (without the <strong>#me</strong> hash tag) denotes the document describing the agent  who is the referent of the
```

2024-03-18 15:11 UTC, jacoscaz commented
Thank you @TallTed for reviewing!

2024-03-18 15:30 UTC, TallTed requested changes

2024-03-18 15:30 UTC, TallTed commented on spec/identity/index.bs
> +directs the World Web Consortium:
```suggestion
directed the World Web Consortium: 
```

2024-03-18 15:30 UTC, TallTed commented on spec/identity/index.html
> +directs the World Web Consortium: <a href="https://www.w3.org/People/Berners-Lee/card#i">https://www.w3.org/People/Berners-Lee/card#i</a> .</p>
```suggestion
directed the World Web Consortium: <a href="https://www.w3.org/People/Berners-Lee/card#i">https://www.w3.org/People/Berners-Lee/card#i</a>.</p>
```

2024-03-18 15:31 UTC, TallTed commented
Something odd in the .bs to .html process inserted a space before a period. That process should be fixed.

2024-03-26 14:01 UTC, TallTed commented
I am somewhat concerned about replacing [the original diagram](https://www.researchgate.net/figure/WebID-Description-134_fig2_282876891) with this significantly reduced diagram, without having the alternatives visible side-by-side.

The original is [directly linked here](https://www.researchgate.net/profile/Nuno-Bettencourt/publication/282876891/figure/fig2/AS:669547405254679@1536643949808/WebID-Description-134.ppm), but I was not able to make it display live on GitHub.

The original was trying (in part) to explain (without naming) [HTTPRange-14](https://dbpedia.org/page/HTTPRange-14) (also see its [full Wikipedia entry](https://en.wikipedia.org/wiki/HTTPRange-14)), and so tried to diagram the connections between a 4Dspace human (TimBL, illustrated in the diagram as a photograph which was meant to represent the human world, not meant to be interpreted as that photograph itself), the identifier/named/denoter of that human (his WebID URI, `http://www.w3.org/People/Berners-Lee/card#i` [note: `#i`]), the identifier of the representational/profile/description document (now to be called his _WebID Document_, identified/denoted/named by a URL, `http://www.w3.org/People/Berners-Lee/card` [note: no `#i`]).

2024-05-28 13:12 UTC, closed without merging