feat: rename WebID Profile Document to WebID Document
w3c/WebID pull request #69
Opened 2024-03-18 10:31 UTC by jacoscaz

This PR addresses the change requested in #20 . While there appears to be a slightly greater consensus in favor of `WebID Document` over `WebID Profile Document`, the difference is so small that feedback to this PR might tilt the balance towards the latter and negate the need for a change. Let's see what happens. 
 
This PR does not introduce any breaking change. Setting the deadline for review in two weeks, on 2024-04-01.

Do not bother reviewing the `spec/identity/index.html` as that's automatically updated by our current CI setup based on the contents of `spec/identity/index.bs`. We'll sort this out in a separate issue / PR.

Links to the rendered files:

- main branch: https://w3c.github.io/WebID/spec/identity/index.html
- this PR: https://htmlpreview.github.io/?https://github.com/jacoscaz/WebID/blob/feat/rename-webid-profile-document-to-webid-document/spec/identity/index.html

2024-03-21 18:30 UTC, TallTed commented on spec/identity/index.bs
> +## Publishing a WebID Document using the RDFa HTML notation ## {#publishing-a-webid-profile-using-the-rdfa-html-notation}
We might want to preserve this fragment identifier, but I think we should also have a new one, better matching the revised section head.
```suggestion
## Publishing a WebID Document using the RDFa HTML notation ## {#publishing-a-webid-profile-using-the-rdfa-html-notation}{#publishing-a-webid-document-using-the-rdfa-html-notation}
```

2024-03-21 18:31 UTC, TallTed commented on spec/identity/index.bs
>  # Processing the WebID Profile # {#processing-the-webid-profile}
as above ... and there may be more
```suggestion
# Processing the WebID Profile # {#processing-the-webid-profile}{#processing-the-webid-document}
```

2024-03-21 18:32 UTC, TallTed requested changes
there were more visible... there may be more *in*visible

2024-03-21 18:32 UTC, TallTed commented on spec/identity/index.bs
> +# Publishing the WebID Document # {#publishing-the-webid-profile-document}
```suggestion
# Publishing the WebID Document # {#publishing-the-webid-profile-document}{#publishing-the-webid-document}
```

2024-03-21 18:32 UTC, TallTed commented on spec/identity/index.bs
> +## WebID Document Vocabulary ## {#webid-profile-vocabulary}
```suggestion
## WebID Document Vocabulary ## {#webid-profile-vocabulary}{#webid-document-vocabulary}
```

2024-03-21 18:32 UTC, TallTed commented on spec/identity/index.bs
> +### Contents of a WebID Document ### {#webid-profile-contents}
```suggestion
### Contents of a WebID Document ### {#webid-profile-contents}{#webid-document-contents}
```

2024-03-21 18:45 UTC, jacoscaz commented
Thank you for reviewing, @TallTed! I'll merge your suggestions tomorrow. I hadn't focused on the small details, yet, as I am unsure as to whether this PR should actually be merged or not. Feedback in #20 is very close, perhaps too close to justify changing the status quo, and I had hoped that opening the PR would have invited more feedback to tilt the balance one way or another.

2024-03-21 18:56 UTC, TallTed commented
I remain on the side of keeping `WebID Profile Document`. But if the change is made at all, I think it should be applied consistently.

2024-03-22 16:13 UTC, TallTed requested changes

2024-03-22 16:13 UTC, TallTed commented on spec/identity/index.bs
> +If a WebID provider would prefer not to mark up his WebID Document in
randomly noticed unnecessary gender specificity
```suggestion
If a WebID provider would prefer not to mark up their WebID Document in
```

2024-03-22 16:38 UTC, jacoscaz commented on spec/identity/index.bs
> +If a WebID provider would prefer not to mark up his WebID Document in
Hah, thanks for catching this @TallTed . I'm trying very hard to change my habits towards gender neutrality but it's a hard battle against the strongly-gendered wiring of my native language!

2024-03-27 12:17 UTC, pmcb55 commented
> ... I had hoped that opening the PR would have invited more feedback to tilt the balance one way or another.

Okey dokey - so I'll just re-iterate my comment from #20 (https://github.com/w3c/WebID/issues/20#issuecomment-2022617258), i.e.:
  "Strong preference for `WebID Document` over `WebID Profile Document` - so +1 to **_removing_** Profile."

And yeah, I totally agree with @TallTed's assertion above that the change should be made consistently throughout.

2024-03-27 12:17 UTC, pmcb55 approved these changes
LGTM

2024-05-28 13:12 UTC, closed without merging