Update profile document access control
w3c/WebID pull request #7
Opened 2022-02-27 13:59 UTC by csarven

Closes #1

2022-02-28 16:14 UTC, TallTed requested changes

2022-02-28 16:14 UTC, TallTed commented on spec/identity/index.html
> +A WebID Profile Document may contain public as well personal information about the agent identified by the WebID.
1. missing "as"
2. "personal" is only applicable to human agents, but WebIDs may also denote software (and other) agents; "private" is therefore a better adjective.
```suggestion
A WebID Profile Document may contain public as well as private information about the agent identified by the WebID.
```

2022-09-04 19:14 UTC, bblfish commented
Ok, as an editorial change this is an improvement. So it should go through.

2022-09-06 04:13 UTC, TallTed commented
I believe @csarven needs to resolve the merge conflicts before it can be merged...

2022-09-06 05:50 UTC, csarven commented
Resolved merge conflict.

2022-09-06 05:56 UTC, merged